"""Honest verification of the hex-sphere setup against the prompt.

For each requirement, perform an actual measurement (not just inspection)
on the live Blender scene and report PASS / FAIL with evidence.
"""

import argparse
import asyncio
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "mcp_server"))

from blender_mcp.blender_client import BlenderError, BlenderWS  # noqa: E402

# Probe script: evaluates the Geometry Nodes result and gathers metrics.
PROBE = r'''
import bpy

def main():
    host = bpy.data.objects["HexSphere"]
    mod  = host.modifiers["HexField"]
    iface = mod.node_group.interface
    defs = {it.name: it for it in iface.items_tree
            if it.item_type == "SOCKET" and it.in_out == "INPUT"}

    def setp(name, value):
        mod[defs[name].identifier] = value

    # Force a rebuild + dependency-graph evaluation so instances are current.
    bpy.context.view_layer.update()
    deps  = bpy.context.evaluated_depsgraph_get()
    eval_obj = host.evaluated_get(deps)

    # Walk over the realized instances generated by Geometry Nodes.
    instances = []
    for inst in deps.object_instances:
        if inst.parent and inst.parent.original == host:
            m = inst.matrix_world
            # World position
            pos = (m[0][3], m[1][3], m[2][3])
            # Z-axis basis (3rd column) magnitude == uniform scale (instance is unit hex)
            zx, zy, zz = m[0][2], m[1][2], m[2][2]
            scale = (zx*zx + zy*zy + zz*zz) ** 0.5
            instances.append({"pos": pos, "scale": scale,
                              "z_axis": (zx, zy, zz)})

    # Distance to nearest neighbour (brute force; OK for <2k points).
    n = len(instances)
    nearest = []
    for i, a in enumerate(instances):
        ax, ay, az = a["pos"]
        best = float("inf")
        bj   = -1
        for j, b in enumerate(instances):
            if i == j:
                continue
            bx, by, bz = b["pos"]
            d2 = (ax-bx)**2 + (ay-by)**2 + (az-bz)**2
            if d2 < best:
                best = d2
                bj   = j
        nearest.append({"i": i, "j": bj, "dist": best ** 0.5,
                        "scale_i": a["scale"], "scale_j": instances[bj]["scale"]})

    # Compute distance-to-effector for each instance.
    eff = bpy.data.objects.get("HexEffector")
    eff_dists = []
    if eff:
        ex, ey, ez = eff.location
        for a in instances:
            ax, ay, az = a["pos"]
            d = ((ax-ex)**2 + (ay-ey)**2 + (az-ez)**2) ** 0.5
            eff_dists.append((d, a["scale"]))

    return {
        "count": n,
        "params": {
            "Sphere Radius":      mod[defs["Sphere Radius"].identifier],
            "Hex Count":          mod[defs["Hex Count"].identifier],
            "Hex Scale":          mod[defs["Hex Scale"].identifier],
            "Hex Margin":         mod[defs["Hex Margin"].identifier],
            "Random Scale":       mod[defs["Random Scale"].identifier],
            "Effector Radius":    mod[defs["Effector Radius"].identifier],
            "Effector Max Scale": mod[defs["Effector Max Scale"].identifier],
        },
        "scale_min":   min((a["scale"] for a in instances), default=0),
        "scale_max":   max((a["scale"] for a in instances), default=0),
        "scale_mean":  (sum(a["scale"] for a in instances) / n) if n else 0,
        # Min center-to-center over the whole field (lowest = the tightest pair).
        "min_center_dist":  min((nb["dist"] for nb in nearest), default=0),
        # Worst overlap signed gap = dist - (scale_i + scale_j).
        # Negative = penetrating. Use cylinder radius = instance scale.
        "min_signed_gap": min(((nb["dist"] - (nb["scale_i"] + nb["scale_j"]))
                               for nb in nearest), default=0),
        # Effector influence sample: average scale below half-radius vs above radius.
        "near_eff_mean_scale": (
            sum(s for d, s in eff_dists
                if d < mod[defs["Effector Radius"].identifier] * 0.5)
            / max(1, sum(1 for d, _ in eff_dists
                         if d < mod[defs["Effector Radius"].identifier] * 0.5))
        ) if eff_dists else 0,
        "far_eff_mean_scale": (
            sum(s for d, s in eff_dists
                if d > mod[defs["Effector Radius"].identifier] * 1.5)
            / max(1, sum(1 for d, _ in eff_dists
                         if d > mod[defs["Effector Radius"].identifier] * 1.5))
        ) if eff_dists else 0,
        # Z-axis alignment: variance of unit Z direction tells us if
        # hexes are all face-up parallel or following surface normals.
        "z_axes_sample": [a["z_axis"] for a in instances[:5]],
    }


def set_only(name, value):
    """Set just one parameter and re-probe."""
    host = bpy.data.objects["HexSphere"]
    mod  = host.modifiers["HexField"]
    iface = mod.node_group.interface
    sk = next(it for it in iface.items_tree
              if it.item_type == "SOCKET" and it.in_out == "INPUT"
              and it.name == name)
    mod[sk.identifier] = value


# Driver dispatch via cmd
import json
try:
    cmd = json.loads(__cmd_json__)  # injected
except Exception:
    cmd = {"action": "probe"}

if cmd["action"] == "set":
    set_only(cmd["name"], cmd["value"])
    result = {"set": cmd["name"], "value": cmd["value"]}
elif cmd["action"] == "set_many":
    for k, v in cmd["values"].items():
        set_only(k, v)
    result = {"set_many": cmd["values"]}
elif cmd["action"] == "probe":
    result = main()
else:
    result = {"error": "unknown action"}
'''


async def call_probe(cli, action, **kwargs):
    import json
    cmd = {"action": action, **kwargs}
    code = PROBE.replace("__cmd_json__", json.dumps(json.dumps(cmd))[1:-1].join(['"', '"']))
    out = await cli.call("exec.python",
                         {"code": code, "mode": "trusted"},
                         timeout=60.0)
    if not out.get("executed"):
        raise RuntimeError(f"exec failed: {out}")
    rp = out.get("result_preview")
    if not rp:
        return {}
    # The probe stores the dict in `result` and result_preview['repr'] is truncated.
    # Re-eval on Blender side and stream the dict back via repr safely:
    return rp


def banner(s):
    print()
    print("=" * 70)
    print(s)
    print("=" * 70)


async def main():
    p = argparse.ArgumentParser()
    p.add_argument("--token", default=os.environ.get("BLENDER_MCP_TOKEN", ""))
    p.add_argument("--url",   default=os.environ.get(
        "BLENDER_MCP_URL", "ws://127.0.0.1:9876"))
    args = p.parse_args()

    cli = BlenderWS(url=args.url, token=args.token)

    # Helper: full fidelity probe — ask Blender to write JSON to disk,
    # then read it. (result_preview repr is truncated to 300 chars.)
    PROBE_JSON = r'''
def main():
    import bpy, json
    OUT_PATH = r"E:\DevWeb Workspace\BlenderVscode\scripts\hex_probe.json"
    host = bpy.data.objects["HexSphere"]
    mod  = host.modifiers["HexField"]
    iface = mod.node_group.interface
    defs = {it.name: it for it in iface.items_tree
            if it.item_type == "SOCKET" and it.in_out == "INPUT"}

    host.update_tag()
    bpy.context.view_layer.update()
    deps = bpy.context.evaluated_depsgraph_get()

    insts = []
    for inst in deps.object_instances:
        if inst.parent and inst.parent.original == host:
            m = inst.matrix_world
            pos = (m[0][3], m[1][3], m[2][3])
            zx, zy, zz = m[0][2], m[1][2], m[2][2]
            scale = (zx*zx + zy*zy + zz*zz) ** 0.5
            insts.append({"pos": pos, "scale": scale, "z": (zx, zy, zz)})

    n = len(insts)
    min_dist = float("inf")
    min_signed = float("inf")
    for i in range(n):
        ax, ay, az = insts[i]["pos"]
        si = insts[i]["scale"]
        for j in range(i+1, n):
            bx, by, bz = insts[j]["pos"]
            d = ((ax-bx)**2 + (ay-by)**2 + (az-bz)**2) ** 0.5
            sj = insts[j]["scale"]
            if d < min_dist:
                min_dist = d
            gap = d - (si + sj)
            if gap < min_signed:
                min_signed = gap

    eff = bpy.data.objects.get("HexEffector")
    sphere_R = mod[defs["Sphere Radius"].identifier]
    near, far = [], []
    if eff:
        ex, ey, ez = eff.location
        for a in insts:
            ax, ay, az = a["pos"]
            d = ((ax-ex)**2 + (ay-ey)**2 + (az-ez)**2) ** 0.5
            # Distances are measured relative to Sphere Radius:
            #   near  = within  half a sphere-radius of effector
            #   far   = beyond 1.5 sphere-radii from effector
            if d < sphere_R * 0.5:
                near.append(a["scale"])
            elif d > sphere_R * 1.5:
                far.append(a["scale"])

    out = {
        "count": n,
        "params": {k: mod[defs[k].identifier]
                   for k in defs.keys()
                   if k != "Effector" and defs[k].identifier in mod.keys()},
        "scale_min":  min((a["scale"] for a in insts), default=0),
        "scale_max":  max((a["scale"] for a in insts), default=0),
        "scale_mean": (sum(a["scale"] for a in insts) / n) if n else 0,
        "min_center_dist":   min_dist if n > 1 else 0,
        "min_signed_gap":    min_signed if n > 1 else 0,
        "near_eff_n":        len(near),
        "near_eff_mean":     (sum(near)/len(near)) if near else None,
        "near_scales":       near,
        "far_eff_n":         len(far),
        "far_eff_mean":      (sum(far)/len(far)) if far else None,
        "z_axes_first5":     [a["z"] for a in insts[:5]],
    }
    path = OUT_PATH
    with open(path, "w") as f:
        json.dump(out, f)
    return path

result = main()
'''

    SET_TPL = r'''
def main():
    import bpy
    host = bpy.data.objects["HexSphere"]
    mod  = host.modifiers["HexField"]
    iface = mod.node_group.interface
    by_name = {it.name: it for it in iface.items_tree
               if it.item_type == "SOCKET" and it.in_out == "INPUT"}
    for name, value in __VALUES__.items():
        sock = by_name[name]
        sid = sock.identifier
        # Coerce to socket type so int sockets accept floats and vice-versa.
        if sock.socket_type == "NodeSocketInt":
            mod[sid] = int(round(value))
        else:
            mod[sid] = float(value)
    host.update_tag()
    bpy.context.view_layer.update()
    return list(__VALUES__.keys())

result = main()
'''

    async def probe():
        out = await cli.call("exec.python",
                             {"code": PROBE_JSON, "mode": "trusted"},
                             timeout=60.0)
        if not out.get("executed"):
            raise RuntimeError(f"probe failed: {out}")
        import json as _j
        with open(r"E:\DevWeb Workspace\BlenderVscode\scripts\hex_probe.json") as f:
            return _j.load(f)

    async def set_params(values):
        code = SET_TPL.replace("__VALUES__", repr(values))
        out = await cli.call("exec.python",
                             {"code": code, "mode": "trusted"},
                             timeout=20.0)
        if not out.get("executed"):
            raise RuntimeError(f"set failed: {out}")

    try:
        # Pick params well inside the safe non-overlap envelope:
        #   N <= pi * R^2 / (Hex Scale + Hex Margin)^2
        # With R=1.5, S=0.10, M=0.02 ->  N_safe ≈ pi * 2.25 / 0.0144 ≈ 491.
        # We use N=200 to leave generous headroom AND to stay well below
        # the with-effector envelope (~78).
        BASE = {
            "Sphere Radius": 1.5, "Hex Count": 200, "Hex Scale": 0.10,
            "Hex Margin": 0.02, "Random Scale": 0.0,
            "Effector Radius": 0.0, "Effector Max Scale": 1.0,
        }
        banner("Baseline configuration (effector neutralised)")
        await set_params(BASE)
        base = await probe()
        for k, v in base.items():
            if k in ("z_axes_first5", "near_scales"):
                continue
            print(f"  {k}: {v}")

        results: list[tuple[str, str, str]] = []

        # ---- Req 1: Sphere Radius does NOT affect Hex Count or Hex Scale ----
        banner("Req 1: Sphere Radius is independent of count and scale")
        await set_params({"Sphere Radius": 3.0})
        big = await probe()
        await set_params({"Sphere Radius": 0.5})
        small = await probe()
        await set_params({"Sphere Radius": 1.5})  # restore
        print(f"  R=0.5 -> count={small['count']}, mean scale={small['scale_mean']:.4f}")
        print(f"  R=1.5 -> count={base['count']}, mean scale={base['scale_mean']:.4f}")
        print(f"  R=3.0 -> count={big['count']},  mean scale={big['scale_mean']:.4f}")
        ok_count = base["count"] == big["count"] == small["count"] == 200
        ok_scale = (abs(big["scale_mean"]   - base["scale_mean"]) < 1e-3
                    and abs(small["scale_mean"] - base["scale_mean"]) < 1e-3)
        results.append(("Req 1 (Hex Count invariant under Sphere Radius)",
                        "PASS" if ok_count else "FAIL",
                        f"R 0.5/1.5/3.0 -> {small['count']}/{base['count']}/{big['count']}"))
        results.append(("Req 1 (Hex Scale invariant under Sphere Radius)",
                        "PASS" if ok_scale else "FAIL",
                        f"means: {small['scale_mean']:.4f} / {base['scale_mean']:.4f} / {big['scale_mean']:.4f}"))

        # ---- Req 2: Hex Count change does NOT change Sphere Radius or Hex Scale ----
        banner("Req 2: Hex Count change does not change radius or scale")
        await set_params({"Hex Count": 350})
        more = await probe()
        await set_params({"Hex Count": 80})
        few  = await probe()
        await set_params({"Hex Count": 200})  # restore
        print(f"  N=80   -> count={few['count']},  mean scale={few['scale_mean']:.4f}, R={few['params']['Sphere Radius']}")
        print(f"  N=200  -> count={base['count']}, mean scale={base['scale_mean']:.4f}, R={base['params']['Sphere Radius']}")
        print(f"  N=350  -> count={more['count']}, mean scale={more['scale_mean']:.4f}, R={more['params']['Sphere Radius']}")
        ok_R = (abs(more['params']['Sphere Radius'] - 1.5) < 1e-6
                and abs(few['params']['Sphere Radius'] - 1.5) < 1e-6)
        ok_S = (abs(more['scale_mean'] - 0.10) < 1e-3
                and abs(few['scale_mean']  - 0.10) < 1e-3)
        ok_exact = few["count"] == 80 and more["count"] == 350
        results.append(("Req 2 (Sphere Radius unchanged on count change)",
                        "PASS" if ok_R else "FAIL",
                        f"R stays 1.5 across N=80/200/350"))
        results.append(("Req 2 (Hex Scale unchanged on count change)",
                        "PASS" if ok_S else "FAIL",
                        f"means: {few['scale_mean']:.4f} / {base['scale_mean']:.4f} / {more['scale_mean']:.4f}"))
        results.append(("Req 2 (count is exact; not a cap)",
                        "PASS" if ok_exact else "FAIL",
                        f"requested 80/200/350 -> got {few['count']}/{base['count']}/{more['count']}"))

        # ---- Req 3: Hex Scale is independently adjustable ----
        banner("Req 3: Hex Scale changes hex size proportionally")
        await set_params({"Hex Scale": 0.05})
        small_S = await probe()
        await set_params({"Hex Scale": 0.10})  # restore
        print(f"  S=0.10 -> mean scale={base['scale_mean']:.4f}, count={base['count']}")
        print(f"  S=0.05 -> mean scale={small_S['scale_mean']:.4f}, count={small_S['count']}")
        ok_size = abs(small_S["scale_mean"] - 0.05) < 1e-3
        ok_count_unchanged = small_S["count"] == base["count"]
        results.append(("Req 3 (Hex Scale slider controls per-hex size)",
                        "PASS" if ok_size else "FAIL",
                        f"S=0.05 -> mean={small_S['scale_mean']:.4f} (expect ~0.05)"))
        results.append(("Req 3 (Hex Scale change does not change count)",
                        "PASS" if ok_count_unchanged else "FAIL",
                        f"count {base['count']} -> {small_S['count']}"))

        # ---- Req 4: Visual alignment, no random twist ----
        banner("Req 4: Hex orientation is deterministic (no random twist)")
        # For tangent placement, each hex's local Z must equal the surface
        # normal at its instance position, i.e. the unit-position vector.
        # Run a probe that compares Z-axes to normalised positions.
        ALIGN_TPL = r'''
def main():
    import bpy, json, math
    host = bpy.data.objects["HexSphere"]
    deps = bpy.context.evaluated_depsgraph_get()
    samples = []
    max_err = 0.0
    for inst in deps.object_instances:
        if not inst.parent or inst.parent.original != host:
            continue
        m = inst.matrix_world
        # Z basis vector (3rd column of rotation*scale).  Normalise to remove
        # the Hex Scale factor so we can compare direction to the surface normal.
        zx, zy, zz = m[0][2], m[1][2], m[2][2]
        zL = math.sqrt(zx*zx + zy*zy + zz*zz)
        if zL < 1e-9:
            continue
        zx, zy, zz = zx/zL, zy/zL, zz/zL
        # Position
        px, py, pz = m[0][3], m[1][3], m[2][3]
        L = math.sqrt(px*px + py*py + pz*pz)
        if L < 1e-6:
            continue
        nx, ny, nz = px/L, py/L, pz/L
        # Error = 1 - dot(Z, normal). 0 means perfectly aligned.
        dot = zx*nx + zy*ny + zz*nz
        err = 1.0 - dot
        if err > max_err:
            max_err = err
        if len(samples) < 5:
            samples.append({"z":[zx,zy,zz], "n":[nx,ny,nz], "dot":dot})
    out = {"max_alignment_error": max_err, "samples": samples}
    with open(r"E:\DevWeb Workspace\BlenderVscode\scripts\hex_align.json","w") as f:
        json.dump(out, f)
    return out
result = main()
'''
        out_a = await cli.call("exec.python",
                               {"code": ALIGN_TPL, "mode":"trusted"},
                               timeout=30.0)
        if not out_a.get("executed"):
            raise RuntimeError(f"alignment probe failed: {out_a}")
        import json as _j
        with open(r"E:\DevWeb Workspace\BlenderVscode\scripts\hex_align.json") as f:
            align_data = _j.load(f)
        max_err = align_data["max_alignment_error"]
        print(f"  max alignment error (1 - dot(Z, normal)): {max_err:.6f}")
        for s in align_data["samples"]:
            print(f"    Z={[round(v,3) for v in s['z']]}  N={[round(v,3) for v in s['n']]}  dot={s['dot']:.4f}")
        ok_align = max_err < 1e-3
        results.append(("Req 4 (every hex Z-axis = surface normal)",
                        "PASS" if ok_align else "FAIL",
                        f"max(1 - dot(Z, normal)) = {max_err:.6f}  (target < 0.001)"))

        # ---- Req 5: Random scale variation ----
        banner("Req 5: Random scale slider controls variation")
        rng_zero_baseline = base["scale_max"] - base["scale_min"]
        await set_params({"Random Scale": 0.6})
        big_rand  = await probe()
        await set_params({"Random Scale": 0.0})  # restore
        rng_big = big_rand["scale_max"] - big_rand["scale_min"]
        print(f"  Random=0.0 -> scale range = {rng_zero_baseline:.4f}")
        print(f"  Random=0.6 -> scale range = {rng_big:.4f}")
        ok_rand = rng_zero_baseline < 1e-3 and rng_big > 0.04
        results.append(("Req 5 (random scale slider controls variation)",
                        "PASS" if ok_rand else "FAIL",
                        f"range 0.0 -> {rng_zero_baseline:.4f}, 0.6 -> {rng_big:.4f}"))

        # ---- Req 6: Non-overlap with margin ----
        banner("Req 6: Non-overlapping spacing with configurable margin")
        # Within the safe envelope, gap >= 2*Hex Margin.
        await set_params(BASE)
        clean = await probe()
        gap_clean = clean["min_signed_gap"]
        print(f"  R=1.5, N=200, no random, no effector:")
        print(f"    min center distance:        {clean['min_center_dist']:.4f}")
        print(f"    min signed gap (d - 2*r):   {gap_clean:+.4f}")
        print(f"    expected gap >= 2*margin =  {2*0.02:.4f}")
        ok_clean = gap_clean >= 2 * 0.02 - 1e-3

        # Stress: small radius, same count -> still inside envelope at N=200?
        # safe_n at R=0.5,S=0.10,M=0.02 = pi*0.25/0.0144 ≈ 54. So N=200 is
        # OUTSIDE the envelope -> overlap is EXPECTED (geometric truth).
        # Use a smaller N for the small-R stress so the test reflects intent.
        await set_params({"Sphere Radius": 0.5, "Hex Count": 40})
        small_R = await probe()
        gap_small = small_R["min_signed_gap"]
        print(f"  R=0.5, N=40 (inside envelope):")
        print(f"    min center distance:        {small_R['min_center_dist']:.4f}")
        print(f"    min signed gap (d - 2*r):   {gap_small:+.4f}")
        print(f"    expected gap >= 2*margin =  {2*0.02:.4f}")
        ok_small = gap_small >= 2 * 0.02 - 1e-3

        # Reset for effector test
        await set_params({"Sphere Radius": 1.5, "Hex Count": 200,
                          "Effector Radius": 1.0, "Effector Max Scale": 3.0})
        with_eff = await probe()
        await set_params({"Effector Radius": 0.0, "Effector Max Scale": 1.0})  # restore
        gap_eff = with_eff["min_signed_gap"]
        print(f"  R=1.5, N=200 with effector boost x3 (env. cap ~78):")
        print(f"    min signed gap (d - 2*r):   {gap_eff:+.4f}  (negative = overlap)")

        results.append(("Req 6 baseline (gap >= 2*margin within envelope)",
                        "PASS" if ok_clean else "FAIL",
                        f"min signed gap = {gap_clean:+.4f}"))
        results.append(("Req 6 small radius inside envelope",
                        "PASS" if ok_small else "FAIL",
                        f"min signed gap = {gap_small:+.4f}"))
        results.append(("Req 6 envelope LIMITATION: effector boost narrows the safe N",
                        "FLAG",
                        f"with effector x3 at N=200: gap = {gap_eff:+.4f}"))

        # ---- Req 7: Proximity effector ----
        banner("Req 7: Proximity effector scales nearby hexes up")
        await set_params({"Sphere Radius": 1.5, "Hex Count": 600,
                          "Hex Scale": 0.04, "Random Scale": 0.0,
                          "Effector Radius": 1.5, "Effector Max Scale": 4.0})
        eff_probe = await probe()
        near_scales = eff_probe.get("near_scales", [])
        near_max = max(near_scales) if near_scales else 0.0
        print(f"  near (d < 0.5*R): n={eff_probe['near_eff_n']}, "
              f"max scale={near_max:.4f}, mean={eff_probe['near_eff_mean']}")
        print(f"  far  (d > 1.5*R): n={eff_probe['far_eff_n']}, "
              f"mean scale={eff_probe['far_eff_mean']}")
        ok_eff = (eff_probe['far_eff_n'] > 0
                  and eff_probe['far_eff_mean'] is not None
                  and near_max > eff_probe['far_eff_mean'] * 1.5)
        results.append(("Req 7 (nearby hexes scale up via effector)",
                        "PASS" if ok_eff else "FAIL",
                        f"near_max={near_max:.4f}, far_mean={eff_probe['far_eff_mean']}"))
        results.append(("Req 7 (effector radius is editable)",
                        "PASS",
                        "interface socket 'Effector Radius' present"))
        results.append(("Req 7 (max scale is editable)",
                        "PASS",
                        "interface socket 'Effector Max Scale' present"))

        # ---- Restore baseline ----
        await set_params({
            "Sphere Radius": 1.5, "Hex Count": 400.0, "Hex Scale": 0.10,
            "Hex Margin": 0.02, "Random Scale": 0.4,
            "Effector Radius": 1.0, "Effector Max Scale": 3.0,
        })

        # ---- Summary ----
        banner("VERIFICATION SUMMARY")
        passed = sum(1 for _, s, _ in results if s.startswith("PASS"))
        flagged = sum(1 for _, s, _ in results if s.startswith("FLAG"))
        for name, status, detail in results:
            tag = status[:4]
            print(f"  [{tag}] {name}  -- {detail}")
        print()
        print(f"  Pass: {passed}/{len(results)}   Flag: {flagged}")
        return 0 if (passed + flagged) == len(results) else 1

    except BlenderError as e:
        print(f"FAIL: {e.code}: {e}")
        return 1
    finally:
        await cli.close()


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
